[package]
name = "iepub-derive"
version = { workspace=true }
edition = { workspace = true }
license = { workspace = true }
description = { workspace = true }

[lib]
proc-macro = true

[dependencies]

