[package]
name = "iepub-cli"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
description = { workspace = true }

[dependencies]
md-5 = {version = "0.10.6", optional = true }
iepub = { path = "../lib", version = "1.3.1" }
